# Generated by Django 4.2.4 on 2023-10-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='patientsappointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'date'), name='appointment'),
        ),
    ]
