# Generated by Django 4.2.4 on 2023-10-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'MON'), ('Tuesday', 'TUE'), ('Wednesday', 'WED'), ('Thursday', 'THU'), ('Friday', 'FRI'), ('Saturday', 'SAT')], max_length=9)),
                ('duration', models.CharField(max_length=2)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyScheduleDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointments', models.IntegerField(default=0)),
                ('appointment_on_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorschedule')),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.monthlyscheduledoctor')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('licence_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=10, null=True)),
                ('specialization', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='monthlyscheduledoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.registerdoctor'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.registerdoctor'),
        ),
        migrations.AddConstraint(
            model_name='monthlyscheduledoctor',
            constraint=models.UniqueConstraint(fields=('doctor', 'month'), name='monthly'),
        ),
    ]
